### ISSUE TITLE
Unknown URL's spamming console

### ISSUE THREAD

**Issue by WardsParadox** [kainjow/Semulov#12]
I just installed the Update (Version 2.0) after running 1.6 for a long time. I noticed in console that both versions were spamming an error of:
unknown URL: smb://user@123.456.789.000/SharePoint (smbfs)

Not sure what this means.

**Comment by kainjow** [comment]
It's a harmless message, mostly for debugging. I'll look into reducing it.

**Comment by WardsParadox** [comment]
Not 100% sure it was related..but during the time it was spamming console I
was having issues keeping the drive mounted. Every 10 minutes that would
spam through and then the drive would disconnect.


Zack

**Comment by kainjow** [comment]
2.1 is released which should fix this. Thanks!
