### ISSUE TITLE
Eject All Tries to eject main hard drive.

### ISSUE THREAD

**Issue by WardsParadox** [kainjow/Semulov#13]
Upon choosing eject all, Semulov presents a popup stating that it could not eject (in my case) "Macintosh HD". Even adding Macintosh HD to the Ignore list fails to stop this.
<img width="532" alt="screen shot 2015-09-29 at 5 15 29 pm" src="https://cloud.githubusercontent.com/assets/8117192/10180781/b115fe4c-66cd-11e5-8baa-22c9ab2b9ded.png">

**Comment by kainjow** [comment]
Are you using the latest version 2.1.1?

**Comment by WardsParadox** [comment]
I did the update and it is fixed. I swear there used to be alerts about the updates but now I'm not sure that's the case. Thank you for pointing out my mistake.

**Comment by kainjow** [comment]
I think the 1.x version didn't have the updater but 2.x does. Glad to know the update fixes it.
