### ISSUE TITLE
Eject all not working

### ISSUE THREAD

**Issue by dyfer** [kainjow/Semulov#14]
Hello Kevin,

Thanks for a great piece of software!

I was using Semulov for a while and after I updated to 2.1.1 (or around that time?) , the eject all function stopped working (both menu and keyboard shortcut) - it just doesn't do anything. I can still eject individual drives using Semulov. I'm on Yosemite 10.10.5. Can I do something to investigate that?

Thanks!
Marcin

**Comment by kainjow** [comment]
Does anything show up in the Console app from Semulov when you choose Eject All?

**Comment by dyfer** [comment]
Thank you for your answer! Since the time I posted I also noted it's not consistent - sometimes Eject All would actually work.

Now one of the drives it never works for is a WD drive that also has a "virtual CD" that mounts automatically.  If I don't place that CD drive under ignored volumes, Semulov prints in the Console

`11/13/15 11:40:23.742 AM Semulov[11852]: Can't get disk for volume: /Volumes/WD SmartWare`

when trying to Eject All.

For one other drive I don't get any posting and Eject All doesn't seem to do anything. But I believe it happen once recently that for yet another drive it worked somehow...

**Comment by neverfox** [comment]
I'm seeing the same thing with 2.3.1 on High Sierra. I have a WD Passport drive with two partitions for Time Machine and external files (both encrypted). I an eject individually but not all. Nothing in the Console for semulov with Eject All.

**Comment by kainjow** [comment]
If this is reproducible with the latest 2.6 please let me know and I can reopen.

**Comment by dyfer** [comment]
I can still see this behavior under version 2.6 with that one WD volume that has a "virtual CD" - Eject All wouldn't eject its data partition (nor the virtual CD, though that's not needed), but I can still eject it individually from Semulov.

**Comment by Stitch7** [comment]
Can confirm this issue on macOS Monterey 12.1 on my Intel MacbookAir 2019. 
I usually have 3 external HDDs connected over my USB-C docking station. "Eject All" disconnects only one of them most of the time, sometimes two. Umounting a single drive also needs multiple attempts every now and then. 
It works much more reliable in Finder.

**Comment by dyfer** [comment]
I now experienced this on a new system (macOS 12.2), in a slightly different drive layout:
- external drive has two volumes
- the first volume is used for data
- the second volume is used for time machine backup 

The time machine backup volume is not being ejected with eject all (but the data volume is being ejected).
Additionally I get a message "Failed to unmount volume <first volume's name>", but the first volume _is_ being in fact unmounted. It's the second (time machine) volume that does not unmont.

**Comment by jaredbm** [comment]
@dyfer I have the same issue but the reverse. My time machine backup will eject (first one listed) but not my other data drive. I have to do them individually which defeats the purpose.

**Comment by miranda** [comment]
I have the same issue with Monterey 12.5 on M1 Mac Mini.  Eject All only ejects one drive.  I have 3 drives and it is the same drive ejected every time regardless of the order I mount them to begin with.  In addition continuing to click Eject All does not eject the remaining drives.
