### ISSUE TITLE
Filter disks

### ISSUE THREAD

**Issue by kainjow** [kainjow/Semulov#16]
> would it be possible to do Regular expression matches on filtering out disks? Or some other solution? All I care about are my external drives and disk images. Mac OS 10.13 has all sorts of recovery disks and different names for “Macintosh HD@snap x” disks showing up.

**Comment by sn0wyfall** [comment]
I am also getting the “Macintosh HD@snap x” disks showing up and sending notifications, at a frequency which unfortunately made me have to turn off the useful notifications.

**Comment by kainjow** [comment]
Just posted a beta with this change if you'd like to test it out: https://github.com/kainjow/Semulov/releases/tag/v2.3-b1
