### ISSUE TITLE
Can't mount encrypted drives

### ISSUE THREAD

**Issue by richardmalone** [kainjow/Semulov#17]
If you try to mount disks encrypted with Filevault it does nothing, even if the password is saved in the Keychain.

**Comment by acecilia** [comment]
Same problem here

**Comment by acecilia** [comment]
Pull request [here](https://github.com/kainjow/Semulov/pull/18)

**Comment by richardmalone** [comment]
Works for me after adding the Security.framework. Thanks.

**Comment by acecilia** [comment]
@richardmalone any guess of how to avoid High Sierra from mounting encrypted disks at startup? Have been googling for 2 days already, but nothing...

**Comment by acecilia** [comment]
@richardmalone As said [here](https://discussions.apple.com/thread/3212415?start=0&tstart=0) (read the last comment in the second page, about High Sierra) and in other places, the fstab method does not seem to work with encrypted devices. Or at least I tried, and it did not work, and people online is reporting the same. If you managed to prevent mounting of an **encrypted** disk, I would love to here about it.

**Comment by acecilia** [comment]
@richardmalone in case you are interested, I managed to setup my disks, so High Sierra does not mount the disk at startup but it is still possible to mount it using Semulov. Find the info [here](https://medium.com/@acecilia/how-to-avoid-mounting-volumes-at-startup-on-macos-high-sierra-d40cfe649fbb) :)

**Comment by kainjow** [comment]
Just posted a beta with this change if you'd like to test it out: https://github.com/kainjow/Semulov/releases/tag/v2.3-b1
