### ISSUE TITLE
Periodic notifications about Boot OS X and Recovery

### ISSUE THREAD

**Issue by neverfox** [kainjow/Semulov#22]
Semulov periodically notifies me that "Boot OS X" and "Recovery" have unmounted and remounted. I'm going to be optimistic and say that this is probably normal OS X background behavior, but the notifications are somewhat annoying since they're essentially noise, especially when waking my computer screen when they've built up. First, is this normal? Second, is there a way to stop semulov from reporting these events with notifications?

OS X 10.13.3 High Sierra
Semulov 2.3.1

**Comment by kainjow** [comment]
You should be able to add them to the Ignored Volumes section in Preferences.
