### ISSUE TITLE
Feature suggestion: Wildcards or RegExs for Ignored Volumes

### ISSUE THREAD

**Issue by noyannus** [kainjow/Semulov#26]
Would be nice to block _classes_ of Volumes from auto mounting, using wildcards or regualar expressions.

Example: Use `^.*TestSystem.*$` or something alike, to block all of: `SierraTestSystem1`, `SierraTestSystem2`, `SierraTestSystem3`, `SierraTestSystem4`, `HighSierraTestSystem1`, `HighSierraTestSystem2`, `HighSierraTestSystem3`, `HighSierraTestSystem4`.

**Comment by kainjow** [comment]
I've wanted to do this for a while. Added a checkbox to interpret the ignored volumes list as regular expressions.
