### ISSUE TITLE
Please offer binary for download while you are in the future

### ISSUE THREAD

**Issue by noyannus** [kainjow/Semulov#27]
Thanks for considering and implementing enhancements!

Now, when trying to open Semulov.xcodeproj with Xcode 9.4.1 on OS 10.13.6, a Dialog appears that says: 
"The project at '[…]/Semulov-master/Semulov.xcodeproj' cannot be opened because it is in a future Xcode project file format. Adjust the project format using a compatible version of Xcode to allow it to be opened by this version of Xcode."

Could you provide a binary for testing?
What Xcode version are you using and where to get it?

**Comment by kainjow** [comment]
Already posted here: https://github.com/kainjow/Semulov/releases

If you follow projects on GitHub you’ll get emailed when releases are posted. I’ll also turn on the auto updates once this version is out of beta.

I’m using Xcode 10 beta.

**Comment by noyannus** [comment]
Thank you!
