### ISSUE TITLE
Can't copy or paste in Ignored Volumes text field…

### ISSUE THREAD

**Issue by noyannus** [kainjow/Semulov#28]
…but typing works.

**Comment by kainjow** [comment]
That's because this usually comes from the Copy and Paste menus in the Edit menu but there is no normal menu bar. You can still right-click to copy/paste.

**Comment by noyannus** [comment]
Ahhh, thank you!

I wonder if there are enough users to warrant an extensive readme to prevent people like me from creating issues all the time. :-) Tentative idea: move "Launch Semulov at login" to the Interface tab (maybe making the Preferences window a bit larger), then you could use the Miscellaneous tab for a help text scroll field; an extra tab for that would not have enough space (or, maybe, just enough, but that would look ugly).
