### ISSUE TITLE
Number of volumes in menu bar

### ISSUE THREAD

**Issue by wlalos** [kainjow/Semulov#32]
After the update to 2.4 a number of volumes shown in the menubar on is always zero on startup. One has to open the menu, then it shows the proper number.

**Comment by kainjow** [comment]
Oops! That is bad. Fixed in 7845f1bf6e95f54c5108d3e60015bdff25888e25 - thanks for reporting.

**Comment by kainjow** [comment]
Post beta here, please let me know if it fixes this: 
https://github.com/kainjow/Semulov/releases/tag/v.2.4.1

**Comment by wlalos** [comment]
2.4.1 seems good.
