### ISSUE TITLE
Semulov no longer respecting the Ignored Volumes list

### ISSUE THREAD

**Issue by Adz0rd** [kainjow/Semulov#33]
Since upgrading to 2.4, Semulov no longer respects the Ignored Volume list and so I am being notified of all the system hidden partitions mounting/unmounting. I have checked and "Use regular expressions" is not checked.

**Comment by kainjow** [comment]
Thanks for reporting. I'll look into it.

**Comment by kainjow** [comment]
Post beta here, please let me know if it fixes this: 
https://github.com/kainjow/Semulov/releases/tag/v.2.4.1

**Comment by Adz0rd** [comment]
Previously I just added the system volumes to the ignored list and it seemed to work. I'll try the beta and will let you know if I notice anymore notifications for the system volumes.
