### ISSUE TITLE
Prevent Semulov from monitoring network volumes

### ISSUE THREAD

**Issue by Adz0rd** [kainjow/Semulov#34]
Hi,

It would be great if I could just have a checkbox that completely ignores network volumes as at the moment, whenever I view a network share (and they get pseudo mounted by Mac OS), they appear in the Semulov menu

**Comment by kainjow** [comment]
Could be done by looking if it's smb, afp, or ftp. Anything else to check for? There is a flag that says whether a mount is local or not, so that logic could be included, but don't think it could be exclusively checked.

**Comment by Adz0rd** [comment]
Sounds good
