### ISSUE TITLE
Prevent Semulov from monitoring soft mounts (loop drives etc.)

### ISSUE THREAD

**Issue by adam-nygate** [kainjow/Semulov#35]
Hi,

It would be great if there were a checkbox to stop Semulov from notifying about mounts for application installs.

**Comment by kainjow** [comment]
I don't think there's a good way to detect this. One could detect mounted disk images and see if the mounted directory only contains one visible item and that that item is a .app folder. If this sounds reasonable, it could be done.

**Comment by Adz0rd** [comment]
Hmm, I feel like it wouldn't be consistent enough. I've seen some apps that have other files also (readme's etc.)

**Comment by kainjow** [comment]
Going to close this. There is no consistent standard for this. Potentially we could add more sophisticated ignore rules in the future that could accommodate this instead of baking more custom logic into the code.
