### ISSUE TITLE
Eject All menu item hot key doesn't seem to work

### ISSUE THREAD

**Issue by brandonedling** [kainjow/Semulov#37]
Running 10.14.2 release and 2.5 of Semulov. Everything is cool except the Eject All hotkey doesn't seem to work.

**Comment by louisparks** [comment]
same issue, eject all shortcut doesn't seem to work

**Comment by kavehv** [comment]
+1

**Comment by kainjow** [comment]
Damn, looks like it's been broken for a while, since 106a46d6e525f189895a7845d7a3e0400e72c877. Should be fixed now.

**Comment by erikw** [comment]
In version `2.4.1` on macOS 10.15.4, Eject All does not work while individual ejects works (like described in this issue).

Is the fix included in this version that I use?

**Comment by kainjow** [comment]
> In version `2.4.1` on macOS 10.15.4, Eject All does not work while individual ejects works (like described in this issue).
> 
> Is the fix included in this version that I use?
> 
> BTW this is a wonderful app! As I have a TimeMachine disk connected at all times, and some times other external drives, it's super to be able to eject them with a keyboard shortcuts when I need to run somewhere with my laptop!

See #24.
