### ISSUE TITLE
Mounts counter little issues

### ISSUE THREAD

**Issue by ponyspy** [kainjow/Semulov#38]
1. Mounts counter, still black when open context menu, please fix

![2019-02-23 21 28 04](https://user-images.githubusercontent.com/870271/53290222-fc1cdd80-37b1-11e9-83c0-5172959d1ff7.png)

2. Maybe make option to hide counter if no mount volumes?

Thanks!

**Comment by kainjow** [comment]
What macOS version are you on? I saw the same text color issue with 10.14 and was able to fix it, but I think the fix requires 10.10 or greater so I bumped the minimum version to that.

**Comment by ponyspy** [comment]
My version 10.14.3

**Comment by kainjow** [comment]
This was fixed.
