### ISSUE TITLE
App not buildable from repo.

### ISSUE THREAD

**Issue by resuna** [kainjow/Semulov#39]
Building the app from repo requires fiddling with signing certificates, which is annoying, then we get this error:

error: Build input file cannot be found: '/.../git/Semulov/Dependencies/NSAppLoginItems/Source/NSApplication+LoginItems.m'

Can you provide necessary files and instructions for building in the README.md?

**Comment by kainjow** [comment]
Can you try the `dist.sh` script in the root of the repo?

**Comment by resuna** [comment]
Same result:

error: Build input file cannot be found: '/Users/peter/git/Semulov/Dependencies/NSAppLoginItems/Source/NSApplication+LoginItems.m'

** BUILD FAILED **

**Comment by resuna** [comment]
If I clean the tree, restoring the original xcode files it fails even earlier:

Ophion:Semulov peter$ sh dist.sh
Build settings from command line:
    SYMROOT = /Users/peter/git/Semulov/Build

note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: No certificate matching 'Developer ID Application: Kevin Wojniak' found: Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning. (in target 'Semulov')

** BUILD FAILED **

**Comment by kainjow** [comment]
I think I fixed the NSApplication+LoginItems.m issue. Can you try again with top of master?

As for the code signing issue, you'll need to change the Code Signing Identity field for the Semulov target in Xcode. You could try "Sign to Run Locally" if you don't have a Developer ID.

**Comment by resuna** [comment]
Now I can't figure out how to get XCode to let me "Sign to run locally" again. If I set the code signing style to "automatic" it says:

Signing for "Semulov" requires a development team. Select a development team in the project editor. (in target 'Semulov').

If I enter a random name for the development team it keeps telling me the same thing.

If I set it to "Manually" it goes back to complaining about your certificate.

**Comment by resuna** [comment]
> Signing for "Semulov" requires selecting either a development team or a provisioning profile. Select a development team or a provisioning profile in the project editor. (in target 'Semulov')

**Comment by resuna** [comment]
I had to manually remove these lines from the pbxproj to get past that.

`-                               TargetAttributes = {
-                                       8D1107260486CEB800E47090 = {
-                                               ProvisioningStyle = Manual;
-                                       };
-                                       A5B58DD8227F8C0C0050DB40 = {
-                                               CreatedOnToolsVersion = 10.2.1;
-                                       };
-                               };
`

Which brought me back to this error:

error: Build input file cannot be found: '/Users/peter/git/Semulov/Dependencies/NSAppLoginItems/Source/NSApplication+LoginItems.m'

**Comment by kainjow** [comment]
I'm not really sure what's going on. I still can't reproduce with Xcode 11.2 after cleaning and wiping out the Dependencies folder. Since no one else has reported, I'll close for now.

**Comment by kainjow** [comment]
I figured it out. The .gitignore file was ignoring changes to the Xcode workspace file, which stores settings about which build system to use. Xcode 10 (or 9) introduced a new build system that may have been turned on in some cases somehow, but this setting file was ignored so the change was never seen in git. The project currently doesn't work with the new setting, so if it was turned on, you'd see the error you were seeing. I will fix this and revert to the legacy build system for now until I can make it work with the new one.

**Comment by resuna** [comment]
Whee. I'll check it out when I get a chance.
