### ISSUE TITLE
Feature suggestion: NTFS mounting

### ISSUE THREAD

**Issue by eatrocks** [kainjow/Semulov#41]
I wonder if it would be appropriate, and if you would be willing to integrate the ability to mount NTFS volumes as read/write. Not loading a driver but using the already existing functionality of MacOS like "Mounty"

**Comment by kainjow** [comment]
It's an interesting idea, but I don't plan on incorporating this feature. It seems risky due to use of `sudo` and turning on read/write that's off by default (I'm sure there's a reason it's read-only and has been for years).
