### ISSUE TITLE
Eject All not working for all volumes

### ISSUE THREAD

**Issue by ukrutt** [kainjow/Semulov#42]
I have an external SSD with a few partitions/volumes on it, and when I hit "Eject All", one of the volumes ends up not ejected.  I'm able to eject it manually.

There are 4 volumes in total; 3 of them are APFS volumes in an APFS container and the last one is an encrypted HFS+ volume - in DiskUtility it's listed as a "CoreStorage Logical Volume". I use the last one for TimeMachine.

The 3 APFS volumes get ejected, but the HFS+ volume does not.

Possibly related: #14 

(Other than this -- great program! Thanks for making it available!)

**Comment by kainjow** [comment]
yes it's a known issue. unfortunately I wrote Semulov years ago when I worked with external drives all the time, but I no longer do, so it's harder to keep this app updated and tested.

I'm going to close this as it's technically a duplicate. Thanks for the feedback.
