### ISSUE TITLE
Feature request: Option to eject entire disk

### ISSUE THREAD

**Issue by petebocken** [kainjow/Semulov#43]
Now that we are living with multiple APFS volumes in Catalina. Set option in preferences to eject entire disk when a single partition is selected to eject.

For example: disk contains "Peter Backup 2" and "Peter Backup 2 - Data". When "Peter Backup 2" is clicked to eject "Peter Backup 2 - Data" as well.

https://p110.p2.n0.cdn.getcloudapp.com/items/nOuNP9gJ/Screen+Shot+2020-03-09+at+8.18.29+AM.png?v=65964d52047b0734c90a05f1b739e6e2

**Comment by kainjow** [comment]
Check out the "Show alternative disks layout" option in the Preferences, that might provide what you want.
