### ISSUE TITLE
volumen unmounted recovery  Catalina issue

### ISSUE THREAD

**Issue by ronniechile** [kainjow/Semulov#44]

**Comment by ronniechile** [comment]
this happens when open system preferences

**Comment by kainjow** [comment]
I'm not sure I understand. Can you provide more details, and/or a screenshot?

**Comment by ronniechile** [comment]
HI, Every time I opened preferences, it appeared UNMOUNTING recovery


already solved by: WRITING RECOVERY IN IGNORED VOLUMEN,
CONGRATULATIONS FOR THE SOFTWARE ,
I'VE BEEN LOOKING FOR SOMETHING LIKE THIS FOR A LONG TIME.
THANKYOU.

**Comment by kainjow** [comment]
Great, I'm going to close since it sounds like the ignored volume feature works for you.

**Comment by ronniechile** [comment]
yes, thankyou

**Comment by ghost** [comment]
hi, its possible a create an unmounted Macitosh HD-DATA in Preferences It
is the only thing that the software lacks

thank you
