### ISSUE TITLE
Shortcut nor working on MacOS Catalina 10.15.2

### ISSUE THREAD

**Issue by rsanjuan87** [kainjow/Semulov#45]
I have setted various cominations and none works for eject all

**Comment by ogerardin** [comment]
Same here, Catalina 10.15.6

**Comment by kainjow** [comment]
I think this is a dupe of #37. Can you test out with the 2.6 beta? https://github.com/kainjow/Semulov/releases/tag/v2.6.0b1

**Comment by ogerardin** [comment]
Confirmed working with 2.6 beta 2
